---
name: POD2-CN
version: 0.01
author:
  - 'PerlChina Team <china-pm@pm.org>'
abstract: Chinese translation of Perl core documentation
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  POD2::CN:
    file: lib/POD2/CN.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
